services:
  app:
    build: .
    container_name: laravel_prod
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./syncn.sql:/usr/local/bin/syncn.sql:ro
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$$MYSQL_ROOT_PASSWORD --silent"]
      interval: 5s
      retries: 5
    volumes:
      - mysql_data:/var/lib/mysql
      - ./syncn.sql:/docker-entrypoint-initdb.d/syncn.sql:ro

volumes:
  mysql_data:
